local_costmap:
  # 局部代价地图的参考坐标系。通常设置为 'odom'。
  # 'odom' 坐标系比 'map' 坐标系更平滑，频率更高，适合作为局部规划的参考，可以避免AMCL定位跳变带来的影响。
  global_frame: odom
  # 机器人的基座坐标系。
  robot_base_frame: base_footprint

  # 更新和发布的频率。
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  # 关键参数！'false' 表示局部代价地图不基于静态地图，完全由实时传感器数据生成。
  static_map: false
  # 关键参数！'true' 表示局部代价地图会随着机器人的移动而滚动，始终保持机器人在中心。
  rolling_window: true

  # 局部代价地图的尺寸 (米)。这个窗口的大小决定了机器人能“看”多远来进行实时避障。
  width: 3
  height: 3
  # 局部代价地图的分辨率 (米/像素)。
  resolution: 0.05

